# xiaoxi-dreams Dream v2 执行脚本
# Generator-Evaluator 三Agent系统

param(
    [ValidateSet("light", "standard", "full")]
    [string]$Mode = "standard",
    
    [int]$Days = 7,
    
    [int]$MaxIterations = 3
)

$ErrorActionPreference = "Stop"

$WORKSPACE = "$env:USERPROFILE\.openclaw\workspace\xiaoxi-dreams"
$MEMORY_DIR = "$env:USERPROFILE\.openclaw\workspace\memory"
$DOLT = "$env:USERPROFILE\Go\bin\dolt.exe"

Write-Host ""
Write-Host "🌀 xiaoxi-dreams Dream v2" -ForegroundColor Cyan
Write-Host "=" * 60
Write-Host "模式: $Mode | 范围: $Days 天 | 最大迭代: $MaxIterations" -ForegroundColor Gray
Write-Host ""

# ========================================
# Phase 1: Planner Agent
# ========================================
Write-Host "📋 [Planner] 分析触发意图..." -ForegroundColor Yellow

# 读取上次 Dream 状态
$LastDream = $null
try {
    $LastDreamResult = & $DOLT sql -q "SELECT date, health_score FROM dream_sessions ORDER BY date DESC LIMIT 1;" --raw
    Write-Host "  上次健康度: $LastDreamResult" -ForegroundColor Gray
} catch {
    Write-Host "  首次 Dream，无历史" -ForegroundColor Gray
}

# 分析模式
switch ($Mode) {
    "light" {
        $Focus = @("新鲜度", "效率")
        $Expectations = @("快速检查", "轻量报告")
    }
    "standard" {
        $Focus = @("新鲜度", "覆盖度", "连贯度")
        $Expectations = @("完整检查", "标准报告")
    }
    "full" {
        $Focus = @("新鲜度", "覆盖度", "连贯度", "效率", "可达性")
        $Expectations = @("全面检查", "详细报告")
    }
}

Write-Host "  关注维度: $($Focus -join ', ')" -ForegroundColor Gray
Write-Host "  期望: $($Expectations -join ', ')" -ForegroundColor Gray

# ========================================
# Phase 2: Generator Agent (迭代)
# ========================================
Write-Host ""
Write-Host "🤖 [Generator] 生成报告..." -ForegroundColor Yellow

$Iteration = 0
$ReportContent = $null

while ($Iteration -lt $MaxIterations) {
    $Iteration++
    Write-Host ""
    Write-Host "--- 迭代 $Iteration ---" -ForegroundColor Cyan
    
    # 生成报告 (简化版，实际会调用 AI)
    $Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"
    
    # 模拟报告生成
    $HealthScore = 82
    $NewEntries = 5
    $UpdatedEntries = 2
    
    $ReportContent = @"
## 🌀 梦境报告 — $(Get-Date -Format 'yyyy-MM-dd') [草稿 v$Iteration]

### 📊 统计
| 指标 | 数值 |
|------|------|
| 扫描文件 | $Days |
| 新增记忆 | $NewEntries |
| 更新记忆 | $UpdatedEntries |

### ❤️ 健康度: $HealthScore/100

| 维度 | 数值 | 状态 |
|------|------|------|
| 新鲜度 | 0.75 | 🟢 |
| 覆盖度 | 0.80 | 🟢 |
| 连贯度 | 0.72 | 🟢 |
| 效率 | 0.85 | 🟢 |
| 可达性 | 0.78 | 🟢 |

### 🔮 关键洞察

1. **[教训]** exec 配置修改应该用 openclaw config set 而非手动编辑
2. **[决策]** 采用 Generator-Evaluator 架构提升报告质量
3. **[项目]** xiaoxi-dreams v1.3.0 发布完成

### 📝 重要变更

| ID | 类型 | 标题 | 操作 |
|----|------|------|------|
| mem_xxx | lesson | openclaw config set | **新增** |
| mem_xxx | project | xiaoxi-dreams v1.3.0 | **新增** |

### 💡 行动建议

1. **继续完善文档** — 架构图已经完成，需要补充使用指南
2. **考虑 Phase 2 实现** — Generator-Evaluator 系统

---
*Generated by xiaoxi-dreams v2.0 Generator | v$Iteration*
"@
    
    # 保存报告
    $ReportFile = "$WORKSPACE\memory\dream-v2-temp.md"
    $ReportContent | Set-Content $ReportFile
    
    Write-Host "  报告已生成: $ReportFile" -ForegroundColor Gray
    
    # ========================================
    # Phase 3: Evaluator Agent
    # ========================================
    Write-Host ""
    Write-Host "🔍 [Evaluator] 评审报告..." -ForegroundColor Yellow
    
    # 调用 Evaluator 脚本
    $EvalResult = & "$WORKSPACE\scripts\evaluator.ps1" -ReportPath $ReportFile -Verbose
    
    Write-Host ""
    Write-Host "Evaluator 结果: $EvalResult" -ForegroundColor Gray
    
    # 检查是否通过
    if ($LASTEXITCODE -eq 0) {
        Write-Host ""
        Write-Host "✅ 报告通过！迭代 $Iteration 次" -ForegroundColor Green
        break
    }
    elseif ($LASTEXITCODE -eq 1) {
        Write-Host ""
        Write-Host "🟡 需要改进，正在进行第 $($Iteration + 1) 次迭代..." -ForegroundColor Yellow
    }
    else {
        Write-Host ""
        Write-Host "🔴 评分过低，正在进行第 $($Iteration + 1) 次迭代..." -ForegroundColor Red
    }
}

# 超过最大迭代
if ($Iteration -ge $MaxIterations) {
    Write-Host ""
    Write-Host "⚠️ 达到最大迭代次数，强制推送当前版本" -ForegroundColor Yellow
}

# ========================================
# Phase 4: 保存最终报告
# ========================================
Write-Host ""
Write-Host "💾 [Memory] 保存最终报告..." -ForegroundColor Yellow

# 保存到 dream-log
$FinalReport = "$MEMORY_DIR\dream-log.md"
$DraftContent = Get-Content $ReportFile -Raw

$FinalContent = @"
$DraftContent

---
_最终报告 | v2.0 | $Mode 模式 | $Iteration 次迭代_
"@

$FinalContent | Add-Content $FinalReport -Encoding UTF8

# 记录到 Dolt
try {
    & $DOLT sql -q @"
INSERT INTO dream_sessions (id, date, status, health_score, scanned_files, new_entries, updated_entries, completed_at)
VALUES (
    'dream-$(Get-Date -Format 'yyyyMMddHHmmss')',
    CURDATE(),
    'completed',
    $HealthScore,
    $Days,
    $NewEntries,
    $UpdatedEntries,
    NOW()
);
"@
    Write-Host "  Dolt 记录已保存" -ForegroundColor Gray
} catch {
    Write-Host "  Dolt 记录失败: $_" -ForegroundColor Red
}

# 清理临时文件
Remove-Item $ReportFile -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "✅ Dream v2 完成！" -ForegroundColor Green
Write-Host ""

# 输出最终报告
Write-Host "=" * 60 -ForegroundColor Cyan
Write-Host $FinalContent -ForegroundColor White
